"""
    Use code generated by ogrinspect command to initialize GIS data.
    See http://geodjango.org/docs/layermapping.html for more information.
"""
from optparse import make_option

from django.core.management.base import NoArgsCommand, CommandError
from django.contrib.gis.utils import LayerMapping 
from django.core import management
import os
from django.contrib.gis.utils import add_postgis_srs

from core import models


class Command(NoArgsCommand):
    help=''
    option_list= NoArgsCommand.option_list + ()

    def get_version(self):
        return "0.1"

    def handle_noargs(self, **options):
        
        add_postgis_srs(102671)
        
        management.call_command('syncdb')

    	lm = LayerMapping(models.CpdBeats, 'data/maps/cpd_beats/cpd_beats.shp', models.cpdbeats_mapping,transform=True, encoding='iso-8859-1')

    	lm.save(verbose=True)


